services:
  sass-watch:
    container_name: ddev-${DDEV_SITENAME}-sass-watch
    image: michalklempa/dart-sass:latest
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    volumes:
      - ..:/var/www/html
